fix bug
Faraon78/fullstack_project pull request #3
Opened 2022-02-13 19:34 UTC by Faraon78

Fix frontend bug:
1) rewrite AuthenticationForm.component with Formik and yup, display error message
2) add RegisterForm.component
3) rewrite routes with PrivateRoute and PublicRoute
4) put storageName to constants
5) put ORMconfig constant to .env file
6) change Number(data) to +data 
7) remove br tag
8) remove context
9) add .env file to .gitignore

2022-02-15 08:51 UTC, Elizaveta20001 commented on server/client/src/Routes/PublicRoute.js
> +  function PublicRoute({ children, isAuthenticated}) {
Slightly not  implemented correctly, see this link [example](https://dev.to/nilanth/how-to-create-public-and-private-routes-using-react-router-72m#:~:text=The%20private%20route %20component%20is,is%20authenticated%20(Logged%20in).) This component should return route or redirect

2022-02-15 09:54 UTC, Elizaveta20001 commented on server/src/controller/UsersController.ts
> +            console.log("Пользователь найден");
Remove all console logs

2022-02-15 09:54 UTC, Elizaveta20001 commented on server/client/src/Redux/currentUser/currentUser.saga.js
> +      console.log("payload ", payload);
Remove console logs

2022-02-15 09:54 UTC, Elizaveta20001 commented on server/client/src/Pages/UserPage/UserPage.component.jsx
>    let {id} = useParams();
Use const instead of let. You don't change this value

2022-02-15 09:54 UTC, Elizaveta20001 commented on server/src/routes.ts
>      action: "one"
Rename actions: findOneUser, findAllUsers and etc

2022-02-15 09:54 UTC, Elizaveta20001 commented on server/client/src/Routes/PublicRoute.js
> +  function PublicRoute({ children, isAuthenticated}) {
The implementation is not exactly what I wanted, check this [link](https://dev.to/nilanth/how-to-create-public-and-private-routes-using-react-router-72m). This component should return Route or Redirect

2022-02-15 09:54 UTC, Elizaveta20001 commented on server/client/src/Routes/PrivateRoute.js
> +  function PrivateRoute({ children, isAuthenticated }) {
See comments in the public route component

2022-02-15 09:54 UTC, Elizaveta20001 commented on server/client/src/Components/RegisterForm/RegisterForm.component.jsx
> +    const {loading, error, request, clearError}= useHttp();
Replace all logic to the AuthPage this component should only take care of presentation

2022-02-21 16:35 UTC, Elizaveta20001 requested changes

2022-02-21 16:35 UTC, Elizaveta20001 commented on node_modules/.bin/prettier
> +#!/bin/sh
Put all node_modules file to .gitignore

2022-02-21 16:35 UTC, Elizaveta20001 commented on server/src/routes.ts
> +        route: '/getposts',
change to /posts

2022-02-21 16:35 UTC, Elizaveta20001 commented on server/src/routes.ts
> +        method: 'post',
Change this method to put or patch(also read about this requests)

2022-02-21 16:35 UTC, Elizaveta20001 commented on server/src/routes.ts
> +        route: '/updateUser',
change to /users/:id

2022-02-21 16:35 UTC, Elizaveta20001 commented on server/src/entity/Comments.ts
> +    email_commentator: string
camelCase

2022-02-21 16:35 UTC, Elizaveta20001 commented on server/client/src/Pages/ProfilePage/ProfilePage.component.jsx
> +                userName: values.userName,
change to ...values(spread operator)

2022-03-04 15:14 UTC, knxzm reviewed
Нужны изменения

2022-03-04 15:14 UTC, ghost commented on server/.env
> +CLOUDINARY_API_SECRET=EB7Nq90YnQINbi-_JLW-bcEjB7Y
.env file must be added to .gitignore
it is not safe to store environment variables on github

2022-03-04 15:14 UTC, ghost commented on server/client/src/App.jsx
> +                    <Button //кнопка LOGOUT рендерится только если пользователь вошел в систему
all comments related to code must be written in English

2022-03-04 15:14 UTC, ghost commented on server/client/src/App.jsx
> +    }
I think logoutHandler function is redundant. You just invoke logout function and nothing else. It will work if you just pass logout function. I guess

2022-03-04 15:14 UTC, ghost commented on server/client/src/App.jsx
> +    //console.log(token, isAuthenticated);
commented code must be removed

2022-03-04 15:14 UTC, ghost commented on server/client/src/App.jsx
> +    // проверяем есть ли сохраненный токен и нужна ли аутентификация
comments must be in English

2022-03-04 15:14 UTC, ghost commented on server/client/src/App.jsx
> +    //подключаем функцию logout из хука
again comment in Russian

2022-03-04 15:14 UTC, ghost commented on server/client/src/Components/AddPostForm/AddPostForm.component.jsx
> +    // функция для вывода сообщения об ошибке
again comment in Russian

2022-03-04 15:14 UTC, ghost commented on server/client/src/Components/AddPostForm/AddPostForm.component.jsx
> +    const formik = props.formik
it would be much better if you used destructuring of props:

instead of 
   const error = props.error
   const formik = props.formik
   and so on
write: 
   const { error, formik } = props;

2022-03-04 15:14 UTC, ghost commented on server/client/src/Components/AddPostForm/AddPostForm.component.jsx
> +                        ) : null}
it would look better if you removed _null_

instead of

```
 {formik.touched.title && formik.errors.title ? (
      <div className="error-post">
              {formik.errors.title}
      </div>
) : null}
```

you could write like this 

```
{formik.touched.title && formik.errors.title && (
     <div className="error-post">
           {formik.errors.title}
     </div>
)
```

2022-03-04 15:14 UTC, ghost commented on server/client/src/Components/AddPostForm/AddPostForm.component.jsx
> +                        ) : null}
the same here

2022-03-04 15:14 UTC, ghost commented on server/client/src/Components/AuthenticationForm/AuthenticationForm.component.jsx
> +    // функция для вывода сообщения об ошибке
again comment in Russian

2022-03-04 15:14 UTC, ghost commented on server/client/src/Components/AuthenticationForm/AuthenticationForm.component.jsx
> +    const formik = props.formik
please, use destructuring of props

2022-03-04 15:14 UTC, ghost commented on server/client/src/Components/AuthenticationForm/AuthenticationForm.component.jsx
> +                        ) : null}
please, use && instead of ternary operator

2022-03-04 15:14 UTC, ghost commented on server/client/src/Components/AuthenticationForm/AuthenticationForm.component.jsx
> +                            onBlur={formik.handleBlur}
you can use destructuring also for formik

2022-03-04 15:14 UTC, ghost commented on server/client/src/Components/AuthenticationForm/AuthenticationForm.component.jsx
> +                        ) : null}
please, use && instead of ternary operator

2022-03-04 15:14 UTC, ghost commented on server/client/src/Components/AuthenticationForm/AuthenticationForm.component.jsx
> +                            disabled={props.loading}
props destructuring would be better

2022-03-04 15:14 UTC, ghost commented on server/client/src/Components/AuthenticationForm/AuthenticationForm.style.css
> +    text-align: center;
Avoid putting styles on tags. It is a bad practice, this styles will be applies to all tags in a project (in this case to all divs with class auth-header). This will cause style overriding

2022-03-04 15:14 UTC, ghost commented on server/client/src/Components/AuthenticationForm/AuthenticationForm.style.css
> +    padding-top: 25px;
the same here

2022-03-04 15:14 UTC, ghost commented on server/client/src/Components/Post/Post.component.jsx
> +import { useDispatch /*, useSelector */ } from 'react-redux'
remove commented code

2022-03-04 15:14 UTC, ghost commented on server/client/src/Components/Post/Post.component.jsx
> +    //const posts = useSelector((state) => state.posts.posts)
remove commented code

2022-03-04 15:14 UTC, ghost commented on server/client/src/Components/Post/Post.component.jsx
> +    //const users = useSelector((state) => state.users.users)
remove commented code

2022-03-04 15:14 UTC, ghost commented on server/client/src/Components/Post/Post.component.jsx
> +    //const comments = useSelector((state) => state.comments.comments)
remove commented code

2022-03-04 15:14 UTC, ghost commented on server/client/src/Components/Post/Post.component.jsx
> +                    <Typography variant="body2">{post.body}</Typography>
use props destructuring

2022-03-04 15:14 UTC, ghost commented on server/client/src/Components/Post/Post.component.jsx
> +                ))}
it would be better if when there is no comments there was a message about it

2022-03-04 15:14 UTC, ghost commented on server/client/src/Components/Post/Post.component.jsx
> +                                    </React.Fragment>
instead of `<React.Fragment></React.Fragment>` you can use `<></`>. They are equal, but the second option looks better

2022-03-04 15:14 UTC, ghost commented on server/client/src/Components/PostsList/PostsList.component.jsx
> +//import {selectAllPosts, selectPageCountPosts } from '../../Redux/store/selectors'
remove commented code

2022-03-04 15:14 UTC, ghost commented on server/client/src/Components/PostsList/PostsList.component.jsx
> +    const posts = useSelector((state) => state.posts.posts)
I guess, it would be better if you wrote selector in separate file. This will let you reuse you selector and avoid writing it again and again in different components. Read about reselect library and add it to your project

2022-03-04 15:14 UTC, ghost commented on server/client/src/Components/PostsList/PostsList.component.jsx
> +    //const posts = selectAllPosts
remove commented code

2022-03-04 15:14 UTC, ghost commented on server/client/src/Components/PostsList/PostsList.component.jsx
> +    //console.log('Страница ' + props.page)
remove commented code

2022-03-04 15:14 UTC, ghost commented on server/client/src/Components/PostsList/PostsList.component.jsx
> +                                <React.Fragment>{post.body}</React.Fragment>
instead of `<React.Fragment></React.Fragment>` use `<></>`

2022-03-04 15:14 UTC, ghost commented on server/client/src/Components/ProfileForm/ProfileForm.component.jsx
> +    const handleFileInputChange = props.handleFileInputChange
use props destructuring

2022-03-04 15:14 UTC, ghost commented on server/client/src/Components/ProfileForm/ProfileForm.component.jsx
> +                                style={{ height: '100px' }}
avoid using inline styles

2022-03-04 15:14 UTC, ghost commented on server/client/src/Components/ProfileForm/ProfileForm.component.jsx
> +                        </NavLink>
Why do you use Button in NavLink? Please, use NavLink without Button as a child or use Button without NavLink as a parent. Read about useHistory hook from react-router-dom

2022-03-04 15:14 UTC, ghost commented on server/client/src/Components/ProfileForm/ProfileForm.style.css
>  }
avoid putting styles on tags

2022-03-04 15:14 UTC, ghost commented on server/client/src/Components/ProfileForm/ProfileForm.style.css
> +}
instead of form_button, file_field write form-button, file-field (your variant is not accepted css format)

2022-03-04 15:14 UTC, ghost commented on server/client/src/Components/RegisterForm/RegisterForm.component.jsx
> +                            ) : null}
use && instead of ternary operator, also you can create component ErrorText and use it instead of writting the same logic and styles again and again

2022-03-04 15:14 UTC, ghost commented on server/client/src/Components/RegisterForm/RegisterForm.component.jsx
> +                            ) : null}
use && instead of ternary operator

2022-03-04 15:14 UTC, ghost commented on server/client/src/Components/RegisterForm/RegisterForm.component.jsx
> +                            ) : null}
use && instead of ternary operator

2022-03-04 15:14 UTC, ghost commented on server/client/src/Components/RegisterForm/RegisterForm.component.jsx
> +                        </NavLink>
p is used for paragraphs, it would be semantically better to use span instead of p

2022-03-04 15:14 UTC, ghost commented on server/client/src/Components/RegisterForm/RegisterForm.component.jsx
> +    const [open, setOpen] = useState(false)
rename open to isOpen and setOpen to setIsOpen

2022-03-04 15:14 UTC, ghost commented on server/client/src/Components/RegisterForm/RegisterForm.style.css
> +}
use more descriptive names

2022-03-04 15:14 UTC, ghost commented on server/client/src/Components/User/User.component.jsx
> +    const users = useSelector((state) => state.users.users)
create selector using reselect

2022-03-04 15:14 UTC, ghost commented on server/client/src/Components/User/User.component.jsx
> +    console.log(currentUser)
remove console.log

2022-03-04 15:14 UTC, ghost commented on server/client/src/Components/User/User.component.jsx
> +                    Adress: {currentUser.address.city},{' '}
` Adress: {currentUser.address.city},{' '}` remove `{' '}`

2022-03-04 15:14 UTC, ghost commented on server/client/src/Components/UserList/UserList.component.jsx
> +    const users = props.users
use props destructuring

2022-03-04 15:14 UTC, ghost commented on server/client/src/Components/UserList/UserList.component.jsx
> +                                </React.Fragment>
<></> instead of <Reatc.Fragment>

2022-03-04 15:14 UTC, ghost commented on server/client/src/Components/UserList/UserList.style.css
> +}
avoid putting styles on tags

2022-03-04 15:14 UTC, ghost commented on server/client/src/Hooks/http.hook.js
> +            console.log('запустили request')
remove console.log

2022-03-04 15:14 UTC, ghost commented on server/client/src/Hooks/http.hook.js
> +                //console.log(data);
remove commented code

2022-03-04 15:14 UTC, ghost commented on server/client/src/Hooks/http.hook.js
> +                throw e
why do you throw an error in catch block? is there any handler that will catch the error?

2022-03-04 15:14 UTC, ghost commented on server/client/src/Pages/AddPostPage/AddPostPage.component.jsx
> +            console.log(values)
remove console.log

2022-03-04 15:14 UTC, ghost commented on server/client/src/Pages/AddPostPage/AddPostPage.component.jsx
> +            })
does it work as expected when you write `credentials: true`? I guess, it should be `credentials: 'include'`.

2022-03-04 15:14 UTC, ghost commented on server/client/src/Pages/AuthPage/AuthPage.component.jsx
> +    // описываем форму ввода
again comment in Russian

2022-03-04 15:14 UTC, ghost commented on server/client/src/Pages/AuthPage/AuthPage.component.jsx
> +                { credentials: 'true' }
credentials: 'true' ?

2022-03-04 15:14 UTC, ghost commented on server/client/src/Pages/MainPage/MainPage.component.jsx
> +//import {selectAllPosts, selectPageCountPosts } from '../../Redux/store/selectors'
remove commented code

2022-03-04 15:14 UTC, ghost commented on server/client/src/Pages/MainPage/MainPage.component.jsx
> +    //const count = selectPageCountPosts
remove commented code

2022-03-04 15:14 UTC, ghost commented on server/client/src/Pages/MainPage/MainPage.style.css
> +nav {
avoid putting styles on tags

2022-03-04 15:14 UTC, ghost commented on server/client/src/Pages/MainPage/MainPage.style.css
> +.content-pages Button {
does it really work?

2022-03-04 15:14 UTC, ghost commented on server/client/src/Pages/PostPage/PostPage.component.jsx
>  }
why do you need thid page? it actually does nothing

2022-03-04 15:14 UTC, ghost commented on server/client/src/Pages/ProfilePage/ProfilePage.component.jsx
> +        avatar: `${user.avatar}`,
why did you wrap values in ` ${}`?

2022-03-04 15:14 UTC, ghost commented on server/client/src/Pages/ProfilePage/ProfilePage.component.jsx
> +            avatar: Yup.string(),
does this really validates your values?

2022-03-04 15:14 UTC, ghost commented on server/client/src/Pages/ProfilePage/ProfilePage.component.jsx
> +        console.log(file)
remove console.log

2022-03-04 15:14 UTC, ghost commented on server/client/src/Pages/ProfilePage/ProfilePage.component.jsx
> +                { credentials: true }
maybe credentials: 'include'?

2022-03-04 15:14 UTC, ghost commented on server/client/src/Pages/RegisterPage/RegisterPage.component.jsx
> +                { credentials: true }
the same

2022-03-04 15:14 UTC, ghost commented on server/client/src/Pages/RegisterPage/RegisterPage.component.jsx
> +            console.log(data)
remove console.log

2022-03-04 15:14 UTC, ghost commented on server/client/src/Pages/UserListPage/UserListPage.component.jsx
> +    console.log(users)
remove console.log

2022-03-04 15:14 UTC, ghost commented on server/client/src/Pages/UserListPage/UserListPage.component.jsx
> +    const users = useSelector((state) => state.users.users)
create selector using reselect

2022-03-04 15:14 UTC, ghost commented on server/client/src/Pages/UserPage/UserPage.component.jsx
> +    console.log(id)
remove console.log

2022-03-04 15:14 UTC, ghost commented on server/client/src/Pages/UserPage/UserPage.component.jsx
>  }
why do you need this component?

2022-03-04 15:14 UTC, ghost commented on server/client/src/Redux/comments/comments.reducer.js
> +    errorMessage: undefined,
why `undefined`? check the difference between null and undefined

2022-03-04 15:14 UTC, ghost commented on server/client/src/Redux/comments/comments.reducer.js
> +                errorMessage: null,
why do you make erroMessage null if this is an action that is dispatched when there is an error?

2022-03-04 15:14 UTC, ghost commented on server/client/src/Redux/currentUser/currentUser.reducer.js
> +    errorMessage: undefined,
why undefined?

2022-03-04 15:14 UTC, ghost commented on server/client/src/Redux/currentUser/currentUser.reducer.js
> +                errorMessage: null,
why null in failure action?

2022-03-04 15:14 UTC, ghost commented on server/client/src/Redux/posts/posts.reducer.js
> +    errorMessage: undefined,
why undefined?

2022-03-04 15:14 UTC, ghost commented on server/client/src/Redux/posts/posts.reducer.js
> +                errorMessage: null,
why null in failure action?

2022-03-04 15:14 UTC, ghost commented on server/client/src/Redux/posts/posts.saga.js
> +        data = yield data.json()
it is better to use const instead of let. and also use 2 different variables

2022-03-04 15:14 UTC, ghost commented on server/client/src/Redux/store/selectors.js
> +//const countItemOnPage = 6
remove commented code

2022-03-04 15:14 UTC, ghost commented on server/client/src/Redux/users/users.reducer.js
> +    errorMessage: undefined,
undefined?

2022-03-04 15:14 UTC, ghost commented on server/client/src/Redux/users/users.reducer.js
> +                errorMessage: null,
null in failure

2022-03-04 15:14 UTC, ghost commented on server/client/src/Redux/users/users.saga.js
> +        data = yield data.json()
const and 2 variables

2022-03-04 15:14 UTC, ghost commented on server/src/controller/CommentController.ts
>      async all(request: Request, response: Response, next: NextFunction) {
Когда мы реализуем функцию, то описываем некоторое действие, а действия в естественных языках выражаются глаголами. Очевидным следствием является то, что имя функции должно быть глаголом. 
Название all ужасно. Оно не говорит, что делает эта функция. Должно быть что-то в роде findComments или findAllComments (find - глагол означающий, что делает функция, comments - что именно она ищет)

2022-03-04 15:14 UTC, ghost commented on server/src/controller/CommentController.ts
>      async allforPost(request: Request, response: Response, next: NextFunction) {
то же самое

2022-03-04 15:14 UTC, ghost commented on server/src/controller/CommentController.ts
> +    private commentRepository = getRepository(Comments)
почему репозиторий в контроллере? нужна прослойка сервиса

2022-03-04 15:14 UTC, ghost commented on server/src/controller/CommentController.ts
>      async one(request: Request, response: Response, next: NextFunction) {
название ужасно

2022-03-04 15:14 UTC, ghost commented on server/src/controller/CommentController.ts
> +        return this.commentRepository.find()
эта логика будет перенесена в сервис
контроллеры должны только получать запросы, вся обработка выполняется сервисами, сейчас оно ничего кроме поиска в базе не делает, а если придется добавит  более сложную логику?

2022-03-04 15:14 UTC, ghost commented on server/src/controller/CommentController.ts
> +        })
в сервис

2022-03-04 15:14 UTC, ghost commented on server/src/controller/CommentController.ts
> +        return this.commentRepository.findOne(request.params.id)
в сервис

2022-03-04 15:14 UTC, ghost commented on server/src/controller/CommentController.ts
>      async save(request: Request, response: Response, next: NextFunction) {
save что? если это функция добавления она должна называться create или add, если редак4тирования - update или edit (если одна функция используется для добавления и редактирования нужно создать еще один маршрут и функцию, потому что по правилам, когда мы отправляем запрос на добавление мы отправляем  POST запрос, если на редактирование PUT или PATCH

2022-03-04 15:14 UTC, ghost commented on server/src/controller/CommentController.ts
>      async remove(request: Request, response: Response, next: NextFunction) {
remove что?

2022-03-04 15:14 UTC, ghost commented on server/src/controller/CommentController.ts
> +        await this.commentRepository.remove(commentToRemove)
в сервис

2022-03-04 15:14 UTC, ghost commented on server/src/controller/UsersController.ts
> +    //Находим всех пользователей
комментарий на русском

2022-03-04 15:14 UTC, ghost commented on server/src/controller/UsersController.ts
> +    private usersRepository = getRepository(Users)
зачем репозиторий в контроллере?

2022-03-04 15:14 UTC, ghost commented on server/src/controller/UsersController.ts
> +            return users
можно не создавать переменную, а сразу писать `return this.UserServiceInstance.findAllUsersDB()`

2022-03-04 15:14 UTC, ghost commented on server/src/controller/UsersController.ts
> +    //Находим одного пользователя по id
убрать комментарий на русском, везде использовать английский

2022-03-04 15:14 UTC, ghost commented on server/src/controller/UsersController.ts
> +            //const user= await this.UserServiceInstance.findOneUserDB(+id)
убрать  закомментированный код

2022-03-04 15:14 UTC, ghost commented on server/src/controller/UsersController.ts
> +        } catch (err) {}
catch блок пустой? где обработка ошибок? хотя бы вывод в консоль

2022-03-04 15:14 UTC, ghost commented on server/src/controller/UsersController.ts
>      //Регистрация нового пользователя
русский

2022-03-04 15:14 UTC, ghost commented on server/src/controller/UsersController.ts
>      // Вход в систему
русский

2022-03-04 15:14 UTC, ghost commented on server/src/index.ts
> +            //эта функция автоматически создана при инициализации проекта typeORM
русский

2022-03-04 15:14 UTC, ghost commented on server/src/index.ts
> +            ;(app as any)[route.method](
as не использовать, запрещенное слово в typescript. так ts не проверяет твои типы, а верит тебе на слово, зачем тогда ts?
и зачем ; в начале?
any тоже не использовать, стараться подобрать нормальный тип

2022-03-04 15:14 UTC, ghost commented on server/src/index.ts
> +                    const result = new (route.controller as any)()[
as и any

2022-03-04 15:14 UTC, ghost commented on server/src/index.ts
> +                            result !== null && result !== undefined
здесь же можно просто проверить на falsy значение, это включает в себя все

2022-03-04 15:14 UTC, ghost commented on server/src/routes.ts
> +    },*/
убрать завкомменченый код

2022-03-04 15:14 UTC, ghost commented on server/src/service/PostsService.ts
> +        // сохраняем новой Post
русский

2022-03-04 15:14 UTC, ghost commented on server/src/service/UsersService.ts
> +            //проверяем есть ли уже такой пользователь
русский

2022-03-04 15:14 UTC, ghost commented on server/src/service/UsersService.ts
> +            return this.usersRepository.save(newUser)
русский

2022-03-04 15:14 UTC, ghost commented on server/src/service/UsersService.ts
> +            // формируем токен
русский

2022-03-04 15:14 UTC, ghost commented on server/src/service/UsersService.ts
> +            // сохраняем изображение в cloudinary
русский

2022-03-04 15:14 UTC, ghost commented on server/src/service/UsersService.ts
> +    async updateUserDB(request: any) {
any

2022-03-04 15:14 UTC, ghost commented on server/src/service/UsersService.ts
> +            // сохраняем изменения пользователя
русский

2022-03-04 15:14 UTC, knxzm commented on .prettierrc.json
> +    "arrowParens": "always"
в prettier лучше добавить правило, которое автоматически будет расставлять точку с запятой

2022-03-04 15:14 UTC, knxzm commented on server/client/src/App.jsx
> +                </Routes>
это очень странная конфигурация, так никто не делает. зачем в Route передавать PrivateRoute? Нужно создать компонент PrivateRoute, который будет принимать все аргументы и возвращать Route. И потом уже использовать этот созданный PrivateRoute БЕЗ Route. 
+ вместо пропы element я бы использовала component

2022-03-08 14:35 UTC, Faraon78 commented on server/client/src/App.jsx
> +                </Routes>
https://dev.to/iamandrewluca/private-route-in-react-router-v6-lg5
Много аналогичных примеров и ответов на stackoverflow. Хотелось бы увидеть правильный код, так как выдает ошибку: [PrivateRoute] is not a <Route> component. All component children of <Routes> must be a <Route> or <React.Fragment>

2022-03-09 08:23 UTC, knxzm commented on server/client/src/App.jsx
> +                </Routes>
Примерно так будет выглядеть роут
`
<Switch>
    <PrivateRoute isAuthenticated={isAuthenticated} component={Component} path={PAGE} />
    <PrivateRoute isAuthenticated={isAuthenticated} component={AnotherComponent} path={ANOTHER_PAGE} />
</Switch>
`
```
const PrivateRoute = ({
  component: Component,
  path,
  isAuthenticated,
}: PrivateRouteProps) => {
  return (
    <Route
      exact
      render={(props) => {
        if (isAuthLoading) return null;

        if (!isAuthenticated) return <Redirect to={NOT_AUTHORIZED} from={path} />;

        return <Component {...props} />;
      }}
    />
  );
};
```

2022-03-29 15:37 UTC, merged